"""Add Prescription table and relationship

Revision ID: 67b09fbd93ce
Revises: ebf610d8ec39
Create Date: 2025-08-10 15:15:52.144690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b09fbd93ce'
down_revision = 'ebf610d8ec39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription')
    # ### end Alembic commands ###
