"""Add Consultation table

Revision ID: ebf610d8ec39
Revises: 972c51c2886a
Create Date: 2025-08-10 15:09:00.306490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf610d8ec39'
down_revision = '972c51c2886a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_date', sa.DateTime(), nullable=False),
    sa.Column('doctor_notes', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.String(length=200), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation')
    # ### end Alembic commands ###
